#ifndef _BEE32_CONFIG_H
#define _BEE32_CONFIG_H

// HAL drivers
#ifndef CONFIG_HAL_DRIVER_BLUETOOTH
#define CONFIG_HAL_DRIVER_BLUETOOTH 1
#endif

#ifndef CONFIG_HAL_DRIVER_WIFI
#define CONFIG_HAL_DRIVER_WIFI 1
#endif

#ifndef CONFIG_HAL_DRIVER_SSD1306
#define CONFIG_HAL_DRIVER_SSD1306 1
#endif

#ifndef CONFIG_HAL_DRIVER_DS3231
#define CONFIG_HAL_DRIVER_DS3231 1
#endif

#ifndef CONFIG_HAL_DRIVER_SCD40
#define CONFIG_HAL_DRIVER_SCD40 1
#endif

#ifndef CONFIG_HAL_DRIVER_MAX72XX
#define CONFIG_HAL_DRIVER_MAX72XX 1
#endif

// Services
#ifndef CONFIG_SERVICE_GUI
#define CONFIG_SERVICE_GUI CONFIG_HAL_DRIVER_SSD1306
#endif

#ifndef CONFIG_SERVICE_HTTP
#define CONFIG_SERVICE_HTTP CONFIG_HAL_DRIVER_WIFI
#endif

#ifndef CONFIG_SERVICE_BLUETOOTH_KEYBOARD
#define CONFIG_SERVICE_BLUETOOTH_KEYBOARD CONFIG_HAL_DRIVER_BLUETOOTH
#endif

#endif